### ISSUE TITLE
[SI-PB9] Atur Jadwal Dokter

### ISSUE THREAD

**Issue by denisgresan** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#10]
Saya sebagai programmer ingin membuat tampilan untuk user dalam mengatur jadwal ke dokter

**Comment by raflyyogas** [comment]
![image](https://user-images.githubusercontent.com/34149177/163950166-28e73d7d-52ec-4c5a-b5d2-843951c88170.png)

**Comment by raflyyogas** [comment]
![image](https://user-images.githubusercontent.com/34149177/163950256-96af25cc-10ab-4811-b6e5-d8c0ef34874d.png)
