### ISSUE TITLE
[S1-PB15] Developing UI Home Page User

### ISSUE THREAD

**Issue by denisgresan** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#23]
Saya sebagai programmer ingin membuat tampilan homepage user untuk kemudahan akses pasien sebagai user utama

**Comment by raflyyogas** [comment]
![image](https://user-images.githubusercontent.com/34149177/163949943-834a11b5-4bcb-4c85-ac78-b7653fc99664.png)
![image](https://user-images.githubusercontent.com/34149177/163949987-77b4bf25-05c0-472e-ba36-a36fd1082938.png)
