### ISSUE TITLE
[S1-PB16] Developing UI Catatan Kesehatan Pasien

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#26]
Saya sebagai programmer ingin membuat tampilan UI Catatan kesehatan pasien agar pasien dapat melihat catatan kesehatan yang diberikan oleh dokter setelah memperoleh pelayanan di Rehab-IN

**Comment by raflyyogas** [comment]
![image](https://user-images.githubusercontent.com/34149177/163950478-ec2813ac-339f-4db5-8c2e-818f9ac8414d.png)
