### ISSUE TITLE
[S3-PB28] Riwayat Pelayanan

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#32]
Sebagai Admin saya ingin melihat dan menghapus riwayat pembayaran layanan yang diberikan pasien, riwayat konsultasi dari dokter, dan riwayat reservasi kamar sehingga dapat memperoleh informasi tentang riwayat pembayaran layanan yang diberikan pasien, riwayat konsultasi dari dokter, dan riwayat reservasi kamar.

![admin-flows-riwayat drawio](https://user-images.githubusercontent.com/65795036/173993356-dad6a58d-c91b-4c68-ac71-a70cc44d4662.png)

![image](https://user-images.githubusercontent.com/65795036/173993626-480d8e68-aca8-4e58-93d1-7764ed81ab62.png)

**Comment by tienfkusumasari** [comment]
done (SP3) catatan tambahkan note bahwa yang disebut layanan adalah semua daftar layanan yang telah dibayar layanan nya
