### ISSUE TITLE
[S3-PB27] Catatan Kesehatan

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#33]
Saya sebagai admin ingin melihat data catatan kesehatan/konsultasi yang diberikan oleh role dokter

![admin-flows-catkes drawio](https://user-images.githubusercontent.com/65795036/171524911-9f1b633c-06ee-4fae-ad72-89581b8a50c4.png)

![image](https://user-images.githubusercontent.com/65795036/173972587-50efdf15-8563-4cab-abd9-c03b8db177d0.png)

**Comment by tienfkusumasari** [comment]
done (SP3) perlu di cek fungsi dan tujuan fitur
