### ISSUE TITLE
[S2-PB24] Kamar RS

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#36]
Sebagai admin, saya ingin melakukan CRUD pada data kamar yang tersedia pada RS sehingga dapat memanajemen data kamar (tipe kamar, fasilitas kamar, serta biaya)

![admin-flows-kamar drawio](https://user-images.githubusercontent.com/65795036/171545222-1c924e58-1895-4d15-a84f-26fc141e64a6.png)

![image](https://user-images.githubusercontent.com/65795036/171576036-34731faa-da2c-4697-a5cf-dda8858a1964.png)
![image](https://user-images.githubusercontent.com/65795036/171576128-06933ee0-4ec0-476f-92dc-bf3f187c7cd9.png)

**Comment by tienfkusumasari** [comment]
close (SP2)
