### ISSUE TITLE
[S3-PB23] Manage Role Dokter

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#37]
Saya sebagai admin ingin melakukan CRU pada role dokter sehingga dapat memanajemen role dokter terkait hak akses serta data profile dan melakukan troubleshoot dari sisi admin
![admin-flows-manage-role-dokter drawio](https://user-images.githubusercontent.com/65795036/171528875-d18a760d-7724-4071-a6db-82da6b83d57b.png)

![image](https://user-images.githubusercontent.com/65795036/173991310-2423c1a8-7eeb-4924-97cf-f13d77af2e50.png)
![image](https://user-images.githubusercontent.com/65795036/173991071-8c0dd217-7d8e-4f7a-b6b5-d4813f62ae06.png)
![image](https://user-images.githubusercontent.com/65795036/173991369-b767960e-373b-49d6-9cc4-ce0b67055562.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
