### ISSUE TITLE
[S3-PB22] Manage Role Pasien

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#38]
Sebagai admin saya ingin melakukan CRU pada role pasien sehingga dapat memanajemen role pasien terkait data profile pasien

![admin-flows-manage-role-pasien drawio](https://user-images.githubusercontent.com/65795036/171529044-ee2d1aef-dc15-4a64-81fa-301f69d624d4.png)

![image](https://user-images.githubusercontent.com/65795036/171540259-213fec27-2177-467d-a94b-bb3c25ebb6c2.png)
![image](https://user-images.githubusercontent.com/65795036/171540080-26f18077-a7ae-45a0-9d7f-e6f11e6c8d76.png)
![image](https://user-images.githubusercontent.com/65795036/173990672-ad42fdb0-6280-4174-970f-030c3eb53380.png)

**Comment by tienfkusumasari** [comment]
done(SP3)
