### ISSUE TITLE
[S3-PB06] Layanan Kami (Booking Jadwal Konsultasi)

### ISSUE THREAD

**Issue by raflyyogas** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#48]
Sebagai user ingin melihat dan melakukan booking untuk konsultasi pada dokter yang tersedia agar melakukan booking untuk konsultasi baik secara online maupun offline

Tombol Online Offline
![image](https://user-images.githubusercontent.com/34149177/175850182-de1225be-5a25-4070-b977-91d924ee6334.png)

Ketika klik tombol offline akan muncul popup modal
![image](https://user-images.githubusercontent.com/34149177/175850261-086e869a-3d86-4148-bfc1-bfc99b6dbd5a.png)

Ketika klik tombol konsultasi online
![image](https://user-images.githubusercontent.com/34149177/175851212-3025d3df-6635-46c7-8daf-e69bdbec535e.png)

Setelah itu tinggal klik Atur jadwalnya
![image](https://user-images.githubusercontent.com/34149177/175851329-92ed88fe-1139-457d-8a6a-64609d023961.png)
![image](https://user-images.githubusercontent.com/34149177/175851398-40fec354-e7bb-4d4e-a335-0ec71393d5e5.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
