### ISSUE TITLE
[S3-PB07] Catatan Kesehatan Pasien

### ISSUE THREAD

**Issue by raflyyogas** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#61]
Sebagai user ingin melihat catatan kesehatan yang berikan oleh dokter agar dapat memperoleh informasi tentang catatan kesehatan sebagai pedoman dalam proses penyembuhan

Alur:
Catatan kesehatan ada ketika pasien sudah di inputkan oleh dokter dengan alur seperti ini:
Pasien akan melihat dibagian catatan kesehatan pada bagian bawah halaman depan pasien kemudian pasian bisa klik selengkapnya pada tombol yang tersedia maka akan muncul halaman isi catatan kesehatannya

Halaman depan:
![image](https://user-images.githubusercontent.com/34149177/175849972-471b13ce-4d40-476e-913f-ca851601cf97.png)

Isi didalam kesehatannya:
![image](https://user-images.githubusercontent.com/34149177/164505224-cbd17566-ec25-4561-8c22-2dbaeb8f2c7a.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
