### ISSUE TITLE
[S3-PB03] Riwayat Pembayaran

### ISSUE THREAD

**Issue by raflyyogas** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#62]
Sebagai user meelihat informasi pembayaran layanan yang diinginkan (baik konsulasi maupun reservasi) agar memperoleh informasi terkait pembayaran yang telah dilakukan terkait layanan yang diinginkan (baik konsultasi maupun reservasi kamar)

Alur:
Ketika ada data order yang dipilih maka akan masuk kedalam Database Order terlebih dahulu -> Ketika itu akan dilihat invoicenya -> mengirimkan file bukti pembayaran -> Datanya akan masuk ke dalam table Database History

- Untuk Riwayat pembayaran kamar
![image](https://user-images.githubusercontent.com/34149177/169231191-58c2264c-8a03-4730-86b5-fed249fe6da2.png)

- Untuk Riwayat pembayaran Dokter
![image](https://user-images.githubusercontent.com/34149177/169231323-a9869a91-07c7-4349-95b4-c1fb1d30846d.png)

![image](https://user-images.githubusercontent.com/34149177/164500911-a25a61b1-7d5b-40f0-914c-4c76b163ee7c.png)
![image](https://user-images.githubusercontent.com/34149177/164500967-61b5bcfa-c664-48b2-8f3f-115cbc8059e8.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
