### ISSUE TITLE
[S3-PB032] Jadwal Konsultasi - Admin Area

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#64]
Saya sebagai admin ingin melakukan CRUD jadwal konsultasi berdasarkan order dari pasien yaitu waktu dan durasi serta atribut dokter yaitu jam kerja yang tersedia untuk penyesuaian durasi yang diinginkan setiap pasien

![admin-flows-jadwal-konsul drawio](https://user-images.githubusercontent.com/65795036/174004170-0ac63ada-8d13-41c0-b7d5-fe53a8da9b8e.png)

![image](https://user-images.githubusercontent.com/65795036/174003575-fd66f834-a786-42b3-8e88-41d6c6e75603.png)
![image](https://user-images.githubusercontent.com/65795036/174003644-28c4361f-6b83-4532-ada6-b53d2fe8e588.png)
![image](https://user-images.githubusercontent.com/65795036/174003707-63007940-6cb9-47a5-9acf-a72a04b5c18b.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
