### ISSUE TITLE
[S3-PB033] Grafik Dashboard Admin

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#65]
Saya sebagai admin ingin melihat ringkasan data pada aplikasi website untuk memperoleh informasi sekilas  tentang data pada aplikasi dengan tampilan grafik

![admin-flows-dashboard-adm drawio](https://user-images.githubusercontent.com/65795036/171571213-16734ddc-77ee-40ee-9400-42f0946a1594.png)

![image](https://user-images.githubusercontent.com/65795036/174002737-a190da70-4a9e-4500-b926-e7b09567486d.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
