### ISSUE TITLE
[S3-PB01] Artikel Kesehatan

### ISSUE THREAD

**Issue by raflyyogas** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#66]
Saya sebagai pasien ingin mendapatkan artikel terkini dari pihak kesehatan.

Alur:
Ada artikel di halaman pasien kemudian pasien akan mengklik judul dari artikel itu sendiri

Halaman Depan
![image](https://user-images.githubusercontent.com/34149177/172751499-05185727-2d8a-4bd5-bfdc-f3f8a1e63627.png)
Halman artikel
![image](https://user-images.githubusercontent.com/34149177/172751610-4b12044f-8b06-4992-85ab-b5956a26c800.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
