### ISSUE TITLE
[S3-PB014] Konsultasi

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#68]
Saya sebagai pasien ingin melakukan konsultasi kepada dokter dengan melakukan order terlebih dahulu, meng-upload bukti pembayaran, hingga menerima pesan tagihan dan link virtual dari admin melalui email. Dalam hal ini, admin kemudian membuat jadwal berdasarkan orderan pasien dan jam kerja dokter. Informasi ini disajikan dalam bentuk table mingguan pada dashboard admin dan dokter. Admin dapat mengedit dan menghapus jadwal yg telah dibuat. Setelah melakukan konsultasi, dokter dapat mengkonfirmasi dengan menggunakan button dari homepage dokter yang dapat menghapus jadwal tersebut. 

![image](https://user-images.githubusercontent.com/65795036/173976521-9360693c-ad9d-446e-93f6-bfdd6f5a03f6.png)
![image](https://user-images.githubusercontent.com/65795036/173976865-6a6b7c16-2c50-431f-bc48-18a235e95a0c.png)
![image](https://user-images.githubusercontent.com/65795036/173976920-7bfac0a1-8ff7-4443-ab41-003bd908a11c.png)
![image](https://user-images.githubusercontent.com/65795036/173976984-6407ef0a-1268-4bd2-b9d9-a72ad419f2b5.png)

**Comment by tienfkusumasari** [comment]
ok (SP3)
