### ISSUE TITLE
[S3-PB034] Orderan Konsultasi dan Kamar

### ISSUE THREAD

**Issue by nurul90042** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#69]
Saya sebagai admin ingin melihat orderan konsultasi dan kamar,lalu memberikan informasi kepada pasien/customer terkait tagihan layanan berupa email dari sisi admin

![image](https://user-images.githubusercontent.com/65795036/173999057-9de58b65-40f8-4caf-b782-2624186cdd4f.png)
![image](https://user-images.githubusercontent.com/65795036/173999082-26c71f76-8f18-490a-a062-33da192e6b15.png)

**Comment by tienfkusumasari** [comment]
done order konsultasi (SP3) 
done order kamar (SP3)
