### ISSUE TITLE
[SI-PB6] Konsultasi Offline/Online

### ISSUE THREAD

**Issue by denisgresan** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#7]
Saya sebagai programmer ingin membuat tampilan dalam mengatur jadwal antara memilih offline / online pada halaman Atur jadwal kepada dokter

**Comment by raflyyogas** [comment]
![image](https://user-images.githubusercontent.com/34149177/163949360-f226f87c-15b0-4572-bda3-b92fbb6bed01.png)
