### ISSUE TITLE
Automated Testing Input Artikel

### ISSUE THREAD

**Issue by raflyyogas** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#71]
Automated tesnting input artikel dengan alur: #66 

Login sebagai admin -> Klik dropdown pada bagian Manajemen Konten -> Klik pada bagian Konten artikel -> Tambahkan Konten Artikel -> Lalu ada muncul modal untuk mengisi konten artikelnya

**Comment by tienfkusumasari** [comment]
close (SP3+1)
