### ISSUE TITLE
[SI-PB7] Reservasi Kamar Pasien

### ISSUE THREAD

**Issue by denisgresan** [SI-RPL-2022/SI4301_GRUP-H_REHAB-IN#8]
Saya sebagai programmer ingin membuat tampilan untuk user dalam reservasi kamar pasien

**Comment by raflyyogas** [comment]
![image](https://user-images.githubusercontent.com/34149177/163949566-f609eac0-e2c9-4ca7-a5fd-69ad4f42f0b7.png)
